#ifndef LIGHTSWITCH_INCLUDE_CONFIGURATION_H_
#define LIGHTSWITCH_INCLUDE_CONFIGURATION_H_

#include <pins_arduino.h>


//// DIGITAL PINS ////
#define PIN_BUTTON            D5
#define PIN_LED_PRIMARY       D6
#define PIN_LED_SECONDARY     D7


#endif //LIGHTSWITCH_INCLUDE_CONFIGURATION_H_
